# 메인 파일 이름을 지정하세요.
main_file = 'main.py'

# 데이타 파일들을 지정하세요.
data_files = [
    'arrow.png',
    'boat_animation.png',
    'paddle.png',
    'sea.png',
    'stone.png',
    'exit.png',
    'heart.png',
    'key_guide.png',
    'main.png',
    'title.png',

    'BGM.mp3',
    'click.wav',
    'close_click.wav',
    'esamanru Bold.ttf',
    'paddle_sound.wav',
    'throw.wav',
    'wounded.wav'
]

# 데이타가 들어있는 폴더들을 지정하세요.
data_folders = [

]